"""3

Revision ID: e4e32fa850a0
Revises: 7a8779e1b9cc
Create Date: 2024-04-24 18:16:29.546807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e32fa850a0'
down_revision = '7a8779e1b9cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
